import os
import io
import base64
import numpy as np
from PIL import Image
from deepface import DeepFace

KNOWN_FACES_DIR = os.path.join(os.path.dirname(__file__), '..', 'known_faces')

def clear_representations_cache():
    """Remove representation pickle files generated by DeepFace.find."""
    if os.path.exists(KNOWN_FACES_DIR):
        for file in os.listdir(KNOWN_FACES_DIR):
            if file.endswith('.pkl'):
                try:
                    os.remove(os.path.join(KNOWN_FACES_DIR, file))
                    print(f"[DEBUG] Cleared representations cache: {file}")
                except Exception as e:
                    print(f"[DEBUG] Error clearing representations cache file {file}: {e}")

def save_face_image(image_bytes, filename):
    """Save uploaded face image to known_faces directory."""
    os.makedirs(KNOWN_FACES_DIR, exist_ok=True)
    filepath = os.path.join(KNOWN_FACES_DIR, filename)
    with open(filepath, 'wb') as f:
        f.write(image_bytes)
    clear_representations_cache()
    
    # Rebuild representations immediately in the background
    import threading
    def rebuild():
        try:
            print("[DEBUG] Rebuilding representations cache in background...")
            DeepFace.find(img_path=filepath, db_path=KNOWN_FACES_DIR, model_name="Facenet", detector_backend="opencv", enforce_detection=False)
            print("[DEBUG] Background rebuild complete.")
        except Exception as e:
            print(f"[DEBUG] Background rebuild error: {e}")
            
    threading.Thread(target=rebuild, daemon=True).start()
    return filepath

def image_bytes_to_path(image_bytes, temp_name="temp_unknown.jpg"):
    """Convert image bytes to a temporary file path for DeepFace."""
    temp_dir = os.path.join(os.path.dirname(__file__), 'temp')
    os.makedirs(temp_dir, exist_ok=True)
    temp_path = os.path.join(temp_dir, temp_name)
    with open(temp_path, 'wb') as f:
        f.write(image_bytes)
    return temp_path

def verify_faces(img1_path, img2_path, model_name="Facenet", detector_backend="opencv"):
    """Verify if two face images belong to the same person."""
    try:
        result = DeepFace.verify(
            img1_path=img1_path,
            img2_path=img2_path,
            model_name=model_name,
            detector_backend=detector_backend,
            enforce_detection=True
        )
        return result
    except Exception as e:
        return {"verified": False, "error": str(e)}

def recognize_face(image_bytes, tolerance=0.4, model_name="Facenet", detector_backend="opencv"):
    """
    Compare face in image against all known faces in database.
    Returns the best matching student.
    """
    # Save unknown face to temp file
    unknown_path = image_bytes_to_path(image_bytes, "temp_unknown.jpg")
    
    # Redundant face detection removed for speed. Liveness check already ensures a face exists,
    # and DeepFace.find will extract the face again anyway.
    
    from database import get_all_students
    
    students = get_all_students()
    print(f"[DEBUG] Loaded students from DB: {students}")
    if not students:
        if os.path.exists(unknown_path):
            os.remove(unknown_path)
        return {"success": False, "message": "No students registered"}
    
    best_match = None
    
    try:
        # Use DeepFace.find for extremely fast bulk comparison using representation cache
        dfs = DeepFace.find(
            img_path=unknown_path,
            db_path=KNOWN_FACES_DIR,
            model_name=model_name,
            detector_backend=detector_backend,
            distance_metric="cosine",
            enforce_detection=True
        )
        print(f"[DEBUG] dfs result: {dfs}")
        
        if len(dfs) > 0 and not dfs[0].empty:
            # The returned dataframe is already sorted by distance ascending
            best_row = dfs[0].iloc[0]
            best_photo_path = os.path.normpath(best_row['identity'])
            best_distance = float(best_row['distance'])
            
            print(f"[DEBUG] Best match found: path={best_photo_path}, distance={best_distance}")
            
            # Find the corresponding student in the DB
            for student in students:
                student_id, name, roll, email, photo_path = student
                if photo_path and os.path.normpath(photo_path) == best_photo_path:
                    best_match = {
                        "student_id": student_id,
                        "name": name,
                        "roll_number": roll,
                        "distance": best_distance,
                        "confidence": float(1 - best_distance)
                    }
                    break
    except Exception as e:
        print(f"[DEBUG] Error during DeepFace.find: {str(e)}")
        best_match = None
    
    # Clean up temp file
    if os.path.exists(unknown_path):
        os.remove(unknown_path)
    
    if best_match and best_match["distance"] <= tolerance:
        return {
            "success": True,
            "student_id": best_match["student_id"],
            "name": best_match["name"],
            "roll_number": best_match["roll_number"],
            "confidence": best_match["confidence"],
            "distance": best_match["distance"]
        }
    
    return {"success": False, "message": "Face not recognized. Please register first."}